from django import forms
from django.core.validators import RegexValidator

class LoginForm(forms.Form):
 username=forms.CharField(label='Usuario o correo')
 password=forms.CharField(label='Contraseña',widget=forms.PasswordInput)
 captcha=forms.CharField(label='Código de seguridad',max_length=6,widget=forms.TextInput(attrs={'autocomplete':'off'}))
class IdentificacionForm(forms.Form):
 paisEmisorId=forms.IntegerField(initial=1,widget=forms.HiddenInput);tipoDocumentoId=forms.IntegerField(label='Tipo de documento',initial=1,widget=forms.Select(choices=((1,'C · Cédula'),(2,'P · Pasaporte'))));documentoNumero=forms.CharField(label='N.º documento',max_length=20)
 primerNombre=forms.CharField(label='Primer nombre',max_length=100);segundoNombre=forms.CharField(label='Segundo nombre',max_length=100,required=False);primerApellido=forms.CharField(label='Primer apellido',max_length=100);segundoApellido=forms.CharField(label='Segundo apellido',max_length=100,required=False);aliasApodo=forms.CharField(label='Alias o apodo',max_length=100,required=False);fechaNacimiento=forms.DateField(label='Fecha de nacimiento',required=False,input_formats=['%d/%m/%Y','%Y-%m-%d'],widget=forms.TextInput(attrs={'placeholder':'dd/mm/aaaa','inputmode':'numeric'}))
 nacionalidadCatalogoId=forms.ChoiceField(label='Nacionalidad');consentimientoDatos=forms.BooleanField(label='Acepto y doy consentimiento para el uso de mis datos',required=False);sexoId=forms.IntegerField(label='Sexo',required=False);referidoId=forms.IntegerField(required=False,widget=forms.HiddenInput);nacionalidadId=forms.IntegerField(required=False,widget=forms.HiddenInput)
 def __init__(self,*a,nacionalidades=(),**k):super().__init__(*a,**k);self.fields['nacionalidadCatalogoId'].choices=nacionalidades
class CorreoForm(forms.Form):correo=forms.EmailField(label='Correo electrónico',max_length=254);principal=forms.BooleanField(label='Correo principal',required=False,initial=True)
class TelefonoForm(forms.Form):
 tipoContactoId=forms.ChoiceField(label='Tipo de teléfono');codigoTelefonicoId=forms.ChoiceField(label='Código');numero=forms.CharField(label='Número',min_length=7,max_length=7,validators=[RegexValidator(r'^\d{7}$','Introduzca exactamente 7 dígitos.')],widget=forms.TextInput(attrs={'inputmode':'numeric','pattern':'[0-9]{7}','maxlength':'7'}));extension=forms.CharField(label='Extensión',max_length=10,required=False);principal=forms.BooleanField(label='Teléfono principal',required=False);usaWhatsapp=forms.BooleanField(label='Usa WhatsApp',required=False)
 def __init__(self,*a,tipos=(),codigos=(),**k):super().__init__(*a,**k);self.fields['tipoContactoId'].choices=tipos;self.fields['codigoTelefonicoId'].choices=codigos
class ResidenciaForm(forms.Form):
 paisId=forms.ChoiceField(label='País');estadoId=forms.ChoiceField(label='Estado');ciudadId=forms.ChoiceField(label='Ciudad',required=False);municipioId=forms.ChoiceField(label='Municipio',required=False);parroquiaId=forms.ChoiceField(label='Parroquia',required=False);tipoSectorId=forms.ChoiceField(label='Tipo de sector',required=False);sectorId=forms.ChoiceField(label='Sector',required=False);codigoPostalId=forms.ChoiceField(label='Código postal',required=False);direccionComplementaria=forms.CharField(label='Dirección complementaria',required=False,max_length=500,widget=forms.Textarea(attrs={'rows':3}))
 def __init__(self,*a,choices=None,**k):super().__init__(*a,**k);choices=choices or {};[setattr(self.fields[f],'choices',choices.get(f,())) for f in ('paisId','estadoId','ciudadId','municipioId','parroquiaId','tipoSectorId','sectorId','codigoPostalId')]
class AcademicoForm(forms.Form):
 nivelId=forms.ChoiceField(label='Nivel académico',required=False);titulo=forms.CharField(label='Título 1',required=False,max_length=250);especialidadId=forms.ChoiceField(label='Especialidad',required=False);titulo2=forms.CharField(label='Título 2',required=False,max_length=250);especialidad2Id=forms.ChoiceField(label='Especialidad 2',required=False);postgrado=forms.BooleanField(label='Postgrado',required=False);descripcionPostgrado=forms.CharField(label='Indique postgrado',required=False,max_length=250);doctorado=forms.BooleanField(label='Doctorado',required=False);descripcionDoctorado=forms.CharField(label='Indique doctorado',required=False,max_length=250);magister=forms.BooleanField(label='Magíster',required=False);descripcionMagister=forms.CharField(label='Indique magíster',required=False,max_length=250);honorId=forms.ChoiceField(label='Honor académico',required=False);ocupacion1=forms.CharField(label='Ocupación 1',required=False,max_length=180);ocupacion2=forms.CharField(label='Ocupación 2',required=False,max_length=180);ocupacion3=forms.CharField(label='Ocupación 3',required=False,max_length=180);disponibilidadId=forms.ChoiceField(label='Disponibilidad',required=False);modalidadId=forms.ChoiceField(label='Modalidad',required=False);whatsapp=forms.CharField(required=False,max_length=100);facebook=forms.CharField(required=False,max_length=250);instagram=forms.CharField(required=False,max_length=250);youtube=forms.CharField(required=False,max_length=250);xTwitter=forms.CharField(label='X (Twitter)',required=False,max_length=250);observacion=forms.CharField(label='Observación',required=False,widget=forms.Textarea(attrs={'rows':3}))
 def __init__(self,*a,c=None,**k):super().__init__(*a,**k);c=c or {};self.fields['nivelId'].choices=c.get('niveles',());self.fields['especialidadId'].choices=c.get('especialidades',());self.fields['especialidad2Id'].choices=c.get('especialidades',());self.fields['honorId'].choices=c.get('honores',());self.fields['disponibilidadId'].choices=c.get('disponibilidades',());self.fields['modalidadId'].choices=c.get('modalidades',())
class GrupoPersonaForm(forms.Form):grupoId=forms.ChoiceField(label='Grupo');
class UsuarioForm(forms.Form):
 username=forms.CharField(label='Usuario',max_length=100);correoAcceso=forms.EmailField(label='Correo',max_length=254);password=forms.CharField(label='Contraseña',widget=forms.PasswordInput);confirmar=forms.CharField(label='Confirmar',widget=forms.PasswordInput)
 def clean(self):d=super().clean();self.add_error('confirmar','Las contraseñas no coinciden.') if d.get('password')!=d.get('confirmar') else None;return d
class InvitacionForm(forms.Form):
 referidoId=forms.ChoiceField(label='Persona que invita');nombre=forms.CharField(required=False);apellido=forms.CharField(required=False);canal=forms.ChoiceField(choices=(('ENLACE','Copiar enlace'),('WHATSAPP','WhatsApp'),('CORREO','Correo')));vigenciaHoras=forms.IntegerField(initial=72,min_value=1,max_value=720)
 def __init__(self,*a,personas=(),**k):super().__init__(*a,**k);self.fields['referidoId'].choices=personas
